[tool.ruff]
lint.select = ["ALL"]

lint.ignore = [
    "D203",  # D211 is incompatible with D203 and D211 have higher priority.
    "D213",  # D212 is incompatible with D213 and D212 have higher priority.
    "ERA001",  # In this project i had to leave some unused code for notes.
]

line-length = 80

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    # You can ignore these rules in tests, but not in source code.
    "S101",  # Usage of assert statements.
]

[tool.flake8]
# You can ignore these rules in tests, but not in source code.
# "WPS110" Wrong variable names.
# "WPS114" Wrong function names.
# "WPS202" Too many module members.
# "WPS210" Too many local variables.
# "WPS218" Too many assert statements.
# "WPS226" String over-use.
per-file-ignores = """
    tests/**/*.py: WPS110, WPS114, WPS202, WPS210, WPS218, WPS226
"""

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"